version: '3.9'

services:
  mountebank:
    image: docker.io/bbyars/mountebank:latest
    ports:
      - "2525:2525"
      - "8080:8080"
    volumes:
      - ./mountebank/imposters:/imposters
      - ./proxy-to-realserver.json:/imposters/proxy-to-realserver.json
    command: ["mb", "--configfile", "/imposters/proxy-to-realserver.json"]
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    working_dir: /app
    command: ["dotnet", "test", "--logger", "console;verbosity=normal" ]
    environment:
      - MY_SERVICE_URL=https://628706e47864d2883e7d2b04.mockapi.io
    # depends_on:
    #   - mountebank
    # depends_on:
    #   - app
