version: '3.9'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      no_cache: true  # add this line to disable cache
    volumes:
      - .:/app
    working_dir: /app
    command: ["dotnet", "test","--no-build"]
    # depends_on:
    #   - app
