version: '3.9'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    working_dir: /app
    command: ["dotnet", "test","--no-build"]
    # depends_on:
    #   - app
