name: Test with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and test with Docker Compose
      run: |
        docker-compose up --abort-on-container-exit --exit-code-from test
